package compiler;

import java.util.ArrayList;
import java.util.List;

import utils.*;

enum Method {
	GET,
	POST
}

enum Version {
	HTTP_1_1,
	HTTP_2
}

public class SemanticHandler {
	//errors and warnings handling
	List<CompilerError> errors;
	List<CompilerError> warnings;
	//generated by request line
	RequestLine requestLine;
	//generated by headers
	List<Header> headers;
	//generated by body
	String body;
	boolean existsBody;
	//final output
	String javaCode;
	
	//constructor
	public SemanticHandler () {
		errors = new ArrayList<CompilerError>();
		warnings = new ArrayList<CompilerError>();
		
		headers = new ArrayList<Header>();
		body = "";
		existsBody = false;
		
		javaCode = "";
	}
	
	public RequestLine createRequestLine(String m, String p, String v) {	
		return new RequestLine(m, p, v);
	}

	public void addRequestLine(RequestLine rl) {
		requestLine = rl;
	}

	public void addHeader(Header hdr) {
		for(Header h: headers)
			if(h.getKey().equals(hdr.getKey()))
					;//ERRORE
		
		headers.add(hdr);
	}

	public String substituteSingleQuote(String text, String s) {
		return text.replaceAll("'", s);
	}
	
	public void addBody(String b) {
		body = b;
		existsBody = true;
	}
	
	public void generateJavaCode() {
		if(existsBody && requestLine.getMethod().equals("GET"))
			; //ERRORE
		
		//first line
		javaCode =  "HttpRequest request = HttpRequest.newBuilder()\n";
		
		//http version
		if(requestLine.getVersion().equals("HTTP/1.1"))
			javaCode += "\t.version(HttpClient.Version.HTTP_1_1)\n";
		else
			javaCode += "\t.version(HttpClient.Version.HTTP_2)\n";
		
		//headers & uri
		String headersStr = "";
		boolean existsHost = false;
		for(Header h: headers) {
			if(h.getKey().equals("Host")) {
				javaCode += "\t.uri(new URI(\"http://" + h.getValue() + requestLine.getPath() + "\"))\n";
				existsHost = true;
			} else {
				headersStr += "\t.header(\"" + h.getKey() +"\", \"" + h.getValue() + "\")\n";
			}
		}
		if(!existsHost)
			;//ERRORE
		javaCode += headersStr;
		
		//method & body
		if(requestLine.getMethod().equals("GET")) {
			javaCode += "\t.GET()\n";
		} else {
			if(existsBody)
				javaCode += "\t.POST(HttpRequest.BodyPublishers.ofString(\"" + body + "\"))\n";
			else
				javaCode += "\t.POST(HttpRequest.BodyPublishers.noBody())\n";
		}
		
		//build
		javaCode += "\t.build();";
	}
	
	public void printJavaCode() {
		System.out.println(javaCode);
	}

	

}
